components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
        - status
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
          maxLength: 200
        description:
          type: string
        price:
          type: integer
          minimum: 0
        tax_rate:
          type: number
          format: float
          default: 0.10
        category_id:
          type: string
        images:
          type: array
          items:
            type: string
            format: uri
        status:
          type: string
          enum:
            - active
            - inactive
            - draft
        stock_quantity:
          type: integer
          minimum: 0
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
          
    ProductCreateRequest:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          maxLength: 200
        description:
          type: string
        price:
          type: integer
          minimum: 0
        tax_rate:
          type: number
          format: float
          default: 0.10
        category_id:
          type: string
        images:
          type: array
          items:
            type: string
            format: uri
        stock_quantity:
          type: integer
          minimum: 0
          default: 0