openapi: 3.1.0
info:
  title: Furupura Shop API
  description: |
    ふるぷらショップ向けAPI

    [← API Portal に戻る](../index.html)
  version: 1.0.0
  contact:
    name: Furupura API Team
    email: api@furupura.jp

servers:
  - url: https://api.furupura.jp/shop/v1
    description: Production
  - url: https://api-staging.furupura.jp/shop/v1
    description: Staging

tags:
  - name: auth
    description: 認証
  - name: products
    description: 商品管理
  - name: orders
    description: 注文管理
  - name: inventory
    description: 在庫管理
  - name: shop
    description: ショップ情報

paths:
  /products:
    $ref: './paths/products.yaml#/~1products'
  /products/{productId}:
    $ref: './paths/products.yaml#/~1products~1{productId}'
  /orders:
    $ref: './paths/orders.yaml#/~1orders'
  /orders/{orderId}/shipping:
    $ref: './paths/orders.yaml#/~1orders~1{orderId}~1shipping'
  /orders/{orderId}/deliver:
    $ref: './paths/orders.yaml#/~1orders~1{orderId}~1deliver'
  /orders/{orderId}/return:
    $ref: './paths/orders.yaml#/~1orders~1{orderId}~1return'
  /orders/{orderId}/cancel:
    $ref: './paths/orders.yaml#/~1orders~1{orderId}~1cancel'
  /auth/signup:
    $ref: './paths/auths.yaml#/~1auth~1signup'
  /auth/login:
    $ref: './paths/auths.yaml#/~1auth~1login'
  /auth/logout:
    $ref: './paths/auths.yaml#/~1auth~1logout'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
