openapi: 3.1.0
info:
  title: Furupura Shop API
  description: ふるぷらショップ向けAPI
  version: 1.0.0
  contact:
    name: Furupura API Team
    email: api@furupura.jp

servers:
  - url: https://api.furupura.jp/shop/v1
    description: Production
  - url: https://api-staging.furupura.jp/shop/v1
    description: Staging

tags:
  - name: products
    description: 商品管理
  - name: orders
    description: 注文管理
  - name: inventory
    description: 在庫管理
  - name: shop
    description: ショップ情報

paths:
  /products:
    $ref: './paths/products.yaml#/~1products'
  /products/{productId}:
    $ref: './paths/products.yaml#/~1products~1{productId}'
  /orders:
    $ref: './paths/orders.yaml#/~1orders'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []