openapi: 3.1.0
info:
  title: Furupura Admin API
  description: |
    ふるぷら管理者向けAPI

    [← API Portal に戻る](../index.html)
  version: 1.0.0
  contact:
    name: Furupura API Team
    email: api@furupura.jp

servers:
  - url: https://api.furupura.jp/admin/v1
    description: Production
  - url: https://api-staging.furupura.jp/admin/v1
    description: Staging

tags:
  - name: auth
    description: 管理者認証
  - name: users
    description: ユーザー管理
  - name: shops
    description: ショップ管理
  - name: analytics
    description: 分析・レポート
  - name: system
    description: システム管理

paths:
  /auth/login:
    $ref: './paths/auth.yaml#/~1auth~1login'
  /users:
    $ref: './paths/users.yaml#/~1users'
  /users/{userId}:
    $ref: './paths/users.yaml#/~1users~1{userId}'
  /shops:
    $ref: './paths/shops.yaml#/~1shops'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []
