openapi: 3.1.0
info:
  title: Furupura User API
  description: ふるぷらユーザー向けAPI
  version: 1.0.0
  contact:
    name: Furupura API Team
    email: api@furupura.jp

servers:
  - url: https://api.furupura.jp/user/v1
    description: Production
  - url: https://api-staging.furupura.jp/user/v1
    description: Staging

tags:
  - name: auth
    description: 認証
  - name: profile
    description: プロフィール管理
  - name: browsing
    description: 商品閲覧
  - name: cart
    description: カート管理
  - name: checkout
    description: 購入手続き

paths:
  /auth/signup:
    $ref: './paths/auth.yaml#/~1auth~1signup'
  /auth/login:
    $ref: './paths/auth.yaml#/~1auth~1login'
  /profile:
    $ref: './paths/profile.yaml#/~1profile'
  /products:
    $ref: './paths/browsing.yaml#/~1products'
  /cart:
    $ref: './paths/cart.yaml#/~1cart'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []