# ショッププロフィール管理
/shop/profile:
  get:
    tags:
      - shop
    summary: 自分のショップ情報取得
    description: 認証済みユーザーが自分のショップの詳細情報を取得します。エリア情報も含まれます。
    operationId: getMyShop
    security:
      - bearerAuth: []
    responses:
      '200':
        description: ショップ情報取得成功
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ShopProfileResponse'
      '404':
        description: ショップが見つかりません
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'
      '401':
        $ref: '../../../shared/responses/common.yaml#/components/responses/Unauthorized'
  put:
    tags:
      - shop
    summary: 自分のショップ情報更新
    description: 認証済みユーザーが自分のショップの情報を更新します。
    operationId: updateMyShop
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/profiles.yaml#/components/schemas/ShopProfileUpdateRequest'
    responses:
      '200':
        description: ショップ情報更新成功
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ShopProfileUpdateResponse'
      '404':
        description: ショップが見つかりません
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'
      '401':
        $ref: '../../../shared/responses/common.yaml#/components/responses/Unauthorized'

# ショップオーナープロフィール管理
/shopowner/profile:
  put:
    tags:
      - shopOwner
    summary: ショップオーナープロフィール更新
    description: ショップオーナーのプロフィール情報を更新します。認証が必要です。更新したいフィールドのみ送信してください。
    operationId: updateShopOwnerProfile
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/profiles.yaml#/components/schemas/ShopOwnerProfileUpdateRequest'
    responses:
      '200':
        description: プロフィール更新成功
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ShopOwnerProfileResponse'
      '404':
        description: ショップオーナーが見つかりません
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'
      '401':
        $ref: '../../../shared/responses/common.yaml#/components/responses/Unauthorized'
      '500':
        description: サーバーエラー
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'

/shopowner/verify-password:
  post:
    tags:
      - shopOwner
    summary: パスワード確認
    description: 現在のパスワードが正しいか確認します。
    operationId: verifyPassword
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/profiles.yaml#/components/schemas/PasswordVerificationRequest'
    responses:
      '200':
        description: パスワードが正しい
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: パスワードが正しいです
              required: [message]
      '401':
        description: パスワードが間違っている
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'

/shopowner/change-password:
  put:
    tags:
      - shopOwner
    summary: パスワード変更
    description: ショップオーナーのパスワードを変更します。現在のパスワードと新しいパスワードが必要です。
    operationId: changePassword
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '../schemas/profiles.yaml#/components/schemas/PasswordChangeRequest'
    responses:
      '200':
        description: パスワード変更成功
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: パスワードを変更しました
              required: [message]
      '400':
        description: バリデーションエラー
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'
      '401':
        description: 現在のパスワードが間違っている
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'
      '500':
        description: サーバーエラー
        content:
          application/json:
            schema:
              $ref: '../schemas/profiles.yaml#/components/schemas/ErrorResponse'
