components:
  schemas:
    PublicProduct:
      type: object
      required:
        - productId
        - name
        - price
      properties:
        productId:
          type: integer
          format: int64
          description: 商品ID
        categoryId:
          type: integer
          description: カテゴリーID
        shopName:
          type: string
          description: ショップ名
        shopArea:
          type: integer
          description: ショップエリアID
        name:
          type: string
          description: 商品名
        description:
          type: string
          description: 商品説明
        image:
          type: string
          format: uri
          description: 商品画像URL
        images:
          type: array
          items:
            type: string
            format: uri
          description: 商品画像URL一覧
        price:
          type: integer
          minimum: 0
          description: 価格
        originalPrice:
          type: integer
          minimum: 0
          description: 定価（セール時のみ表示）
        category:
          type: object
          properties:
            categoryId:
              type: integer
              description: カテゴリーID
            name:
              type: string
              description: カテゴリー名
            categorySlug:
              type: string
              description: カテゴリースラッグ
            parentId:
              type: integer
              description: 親カテゴリーID
        brand:
          type: object
          properties:
            brandId:
              type: string
              description: ブランドID
            name:
              type: string
              description: ブランド名
        area:
          type: object
          properties:
            areaId:
              type: integer
              description: エリアID
            name:
              type: string
              description: エリア名

    ProductDetail:
      type: object
      required:
        - productId
        - name
        - price
      properties:
        productId:
          type: integer
          format: int64
          description: 商品ID
        categoryId:
          type: integer
          description: カテゴリーID
        name:
          type: string
          description: 商品名
        description:
          type: string
          description: 商品説明
        image:
          type: string
          format: uri
          description: メイン商品画像URL
        subImages:
          type: array
          items:
            type: string
            format: uri
          description: サブ商品画像URL一覧
        price:
          type: integer
          minimum: 0
          description: 価格
        originalPrice:
          type: integer
          minimum: 0
          description: 定価（セール時のみ表示）
        gender:
          type: integer
          description: 性別（1:メンズ, 2:レディース, 3:ユニセックス, 4:キッズ）
          enum: [1, 2, 3, 4]
        sizeLabel:
          type: array
          items:
            type: integer
          description: サイズラベル配列
        color:
          type: array
          items:
            type: integer
          description: カラー配列
        condition:
          type: string
          description: 商品状態
        material:
          type: string
          description: 素材
        status:
          type: string
          description: 商品ステータス
          enum: [available, sold, reserved]
        category:
          type: object
          properties:
            categoryId:
              type: integer
              description: カテゴリーID
            name:
              type: string
              description: カテゴリー名
            categorySlug:
              type: string
              description: カテゴリースラッグ
            parentId:
              type: integer
              description: 親カテゴリーID
        brand:
          type: object
          properties:
            brandId:
              type: string
              description: ブランドID
            brandSlug:
              type: string
              description: ブランドスラッグ
            name:
              type: string
              description: ブランド名
        area:
          type: object
          properties:
            areaId:
              type: integer
              description: エリアID
            name:
              type: string
              description: エリア名
        shop:
          type: object
          properties:
            shopSlug:
              type: string
              description: ショップスラッグ
            shopId:
              type: integer
              format: int64
              description: ショップID
            shopName:
              type: string
              description: ショップ名
            shopArea:
              type: integer
              description: ショップエリアID
        tags:
          type: array
          items:
            type: object
            properties:
              tagId:
                type: string
                description: タグID
              name:
                type: string
                description: タグ名
          description: 商品に付与されたタグ一覧
