name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      STORE_PATH: ~/.pnpm-store
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Cache Redocly
        uses: actions/cache@v4
        with:
          path: .redocly-cache
          key: ${{ runner.os }}-redocly-${{ hashFiles('contexts/**/*.yaml', 'redocly.yaml') }}
          restore-keys: |
            ${{ runner.os }}-redocly-

      - name: Validate OpenAPI specs
        run: pnpm run validate:all

      - name: Check code formatting
        run: pnpm run lint

      - name: Build documentation
        run: pnpm run docs:build

      - name: Upload documentation artifacts
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: api-docs
          path: docs/
          retention-days: 7
